version: "3.1"

services:
  postgres:
    image: postgres:latest
    container_name: wmu-postgres
    environment:
      POSTGRES_PASSWORD: postgres-password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: wmu-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@grouvie.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - postgres
